version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_UDER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - "postgres:/d/_system"
    ports:
      - 5432:5432
volumes:
  postgres:
