import React, { FC } from 'react';
import styles from './Home.module.scss';
import {Props as HomePageProps} from '../../pages/index'
import PostsList from '../PostsList/PostsList'
import Head from 'next/head';


interface Props {
  posts: HomePageProps["posts"]
}
const Home: FC<Props> = ({
  posts
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>My New NextApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello Next.js</h1>

      <PostsList posts={posts} />
    </div>
  );
}

export default Home;